
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: "blog/:title"

defaults:
  - scope:
      type: 'posts'
    values:
      layout: post

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - tmp
  - log
  - "*.bat"
  - "*.bak"
  - "*.cfg"
  - "*.json"
