markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  posts:
    output: true
  authors:
    output: true
  archives:
    output: true

defaults:
  - scope:
      type: 'posts'
    values:
      layout: post
      css: post
      permalink: "blog/:title"
      date: "2022-03-01"
      author: 
         name: ptw-cwl
         url: "/ptw-cwl"
      tags:
        -未分类
  - scope:
      type: 'authors'
    values:
      layout: author
      css: author
      permalink: "author/:title"
  - scope:
      type: 'archives'
    values:
      layout: archive
      css: archive
      permalink: "archive/:title"

  
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - tmp
  - log
  - "*.bat"
  - "*.bak"
  - "*.cfg"
  - "*.json"
